### ISSUE TITLE
COLAB

### ISSUE THREAD

**Issue by Valdecy** [manujosephv/deeprenewalprocess#1]
Is it possible to create a minimum COLAB example that will allow anyone to use their own dataset? In the COLAB code the dataset format is not very clear

**Comment by manujosephv** [comment]
DeepREnewal works on the GluonTS Framework. GluonTS has a good tutorial on how to prepare the dataset.

https://ts.gluon.ai/examples/extended_forecasting_tutorial/extended_tutorial.html#1.3-Use-your-time-series-and-features

Can you try following the link? I'll also include the link in the Readme as well.
